spring.application.name=back_end
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Gig_lanka?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sasmitha@1234

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.expiration=864000000000
jwt.secretKey=sdjhfvjslh23741o29iajhscmnaiueghbaxdq37x23vrf92rg2br492ht024wfb9fbciwbf9grfbwibcv29
